---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache (Debian)
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'
      changed_when: false

  tasks:
    - name: Include ansible-role-nnn
      include_role:
        name: "ansible-role-nnn"

  post_tasks:
    - name: Confirm installed version is correct
      shell: echo "{{ git_nnn_latest.tag }}" | grep -F "$(nnn -V)"
      register: nnn_version_check
      failed_when: nnn_version_check.rc != 0
      changed_when: false

  roles:
    - role: geerlingguy.git
