---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: ubuntu-20.04-ansible-role-nnn
    image: ubuntu:20.04
provisioner:
  name: ansible
  log: true
verifier:
  name: ansible
