---
name: Molecule test
on: push 
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04, ubuntu-16.04]
        python-version: [3.7, 3.8]

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt install docker
          python3 -m pip install --upgrade pip
          python3 -m pip install molecule docker
      - name: debug
        run: |
          pwd
          ls
      - name: Test role
        run: |
          molecule test 
        env:
          image: ubuntu
          tag: latest
